INSERT INTO MSS_USER (USER_TYPE, ACTIVE,
 EMAIL, PASSWORD, FIRST_NAME,
  LAST_NAME,DATE_OF_BIRTH, PLACE_OF_BIRTH,
   MOTHERS_NAME, TAJ_NUMBER, GENDER,
  PHONE_NUMBER, AREA_OF_EXPERTISE, RESERVATIONS,
   APPOINTMENTS,REGISTRATION_DATE)
  VALUES ('assistant', 'true'
  ,'doki@gmail.com', 'sCa233ba23+!%', 'Gábor'
  , 'Góra','1974-09-18', 'Szeged',
  'Rác Ilona', '12345078911', 'men',
   '+36706380778', 'pénzügyi_felelős', '3',
   '20',CURRENT_TIME);