INSERT INTO MSS_USER (USER_TYPE, ACTIVE, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME,
 DATE_OF_BIRTH, PLACE_OF_BIRTH, MOTHERS_NAME, TAJ_NUMBER, GENDER,
  PHONE_NUMBER,LANGUAGE,FINANCIAL_BALANSE_huf,REGISTRATION_DATE)
  VALUES ('client', 'true', 'aleeeai@gmail.com', 'sCaba+!%', 'Árpi', 'Balasa',
  '1970-02-18', 'Budapest', 'Pátrik Izolda', '12345118911', 'women',
   '+36706389858','english','250','2023-02-20 10:10:14');

   INSERT INTO MSS_USER (USER_TYPE, ACTIVE, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME,
    DATE_OF_BIRTH, PLACE_OF_BIRTH, MOTHERS_NAME, TAJ_NUMBER, GENDER,
     PHONE_NUMBER,LANGUAGE,FINANCIAL_BALANSE_huf,REGISTRATION_DATE)
     VALUES ('client', 'true', 'dottk@gmail.com', 'sCeqwe8977+!%', 'Zoli', 'Berkes',
     '1967-01-18', 'Szeged', 'Andula Erika', '11881256789', 'women',
      '+36306410058','hungarian','401',CURRENT_TIME);
