INSERT INTO MSS_USER (DTYPE, ACTIVE, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME,
 DATE_OF_BIRTH, PLACE_OF_BIRTH, MOTHERS_NAME, TAJNUMBER, GENDER,
  PHONE_NUMBER,REGISTRATION_DATE, ROLES)
  VALUES ('Client','true', 'aleeeai@gmail.com', 'sCaba+!%', 'Árpi', 'Balasa',
  '1970-02-18', 'Budapest', 'Pátrik Izolda', '12345118911', 'women',
   '+36706389858','2023-02-20 10:10:14','ROLE_CLIENT');

   INSERT INTO MSS_USER (DTYPE, ACTIVE, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME,
    DATE_OF_BIRTH, PLACE_OF_BIRTH, MOTHERS_NAME, TAJNUMBER, GENDER,
     PHONE_NUMBER,REGISTRATION_DATE, ROLES)
     VALUES ('Client', 'true', 'dottk@gmail.com', 'sCeqwe8977+!%', 'Zoli', 'Berkes',
     '1967-01-18', 'Szeged', 'Andula Erika', '11881256789', 'women',
      '+36306410058',CURRENT_TIME,'ROLE_CLIENT');
