INSERT INTO MSS_USER (USER_TYPE, ACTIVE,
 EMAIL, PASSWORD, FIRST_NAME,
  LAST_NAME,DATE_OF_BIRTH, PLACE_OF_BIRTH,
   MOTHERS_NAME, TAJ_NUMBER, GENDER,
  PHONE_NUMBER, AREA_OF_EXPERTISE, RESERVATIONS,
   APPOINTMENTS,REGISTRATION_DATE)
  VALUES ('doctor', 'true'
  ,'doki@gmail.com', 'sCa233ba23+!%', 'Csaba'
  , 'Földi','1970-02-18', 'Szabadka',
  'Rajmunm Ilona', '345678911', 'men',
   '+36706380258', 'sebész', '2',
   '210', '2023-01-10 10:05:25');

   INSERT INTO MSS_USER (USER_TYPE, ACTIVE,  EMAIL, PASSWORD, FIRST_NAME, LAST_NAME,
    DATE_OF_BIRTH, PLACE_OF_BIRTH, MOTHERS_NAME, TAJ_NUMBER, GENDER,
     PHONE_NUMBER, AREA_OF_EXPERTISE, RESERVATIONS, APPOINTMENTS,REGISTRATION_DATE)
     VALUES ('doctor', 'true', 'dokk@gmail.com', 'sCeruiere23+!%', 'Zoli', 'Földi',
     '1967-09-18', 'Szabadka', 'Rák Ilona', '12345678911', 'men',
      '+36306415258', 'idegsebész', '1', '10',CURRENT_TIME);




